const cmd = {
    start: /\/start/,
    generate:/\/generate$/,
    generatePantun:/\/generate_pantun$/,
    quote: /\/quote/,
    quake: /\/gempa/,
    help:/\/help/,
    sick: /^sakit (.*)/,
    onLeave: /^cuti (.*)/,
    izin: /^izin (.*)/,
    fullTeam: /\/masuk_semua$/,
    halfTeam: /\/ada_yang_tidak_hadir$/,
    shiftOne : /\/shift_1$/,
    shiftTwo : /\/shift_2$/,
    shiftThree : /\/shift_3$/,
    groupA : /\/group_A$/,
    groupB : /\/group_B$/,
    groupC : /\/group_C$/,
    groupD : /\/group_D$/,
    insertDb : /\/insert_db$/,
    updateDb : /\/update_db$/,
    deleteDb :  /\/delete_db$/,
    delete : /^delete (.*)/,
    update  : /^update (.*) with (.*)$/,
    insert : /^add (.*)/,
};

module.exports = cmd;